### ISSUE TITLE
Is there some doc on how to do protein-ligand docking with gaudi?

### ISSUE THREAD

**Issue by UnixJunkie** [insilichem/gaudi#1]
Thanks!

**Comment by jaimergp** [comment]
Hi! Congrats on posting the very first issue! 

The docs are hosted at ReadTheDocs and include a [chapter](http://gaudi.readthedocs.io/en/latest/primer.html) on how to face different kind of problems with GaudiMM. Additionally, the Supporting Information contains the input files for the examples commented in the [JCC paper](http://onlinelibrary.wiley.com/doi/10.1002/jcc.24901/full). 

Please ask any further doubt you may have!

**Comment by UnixJunkie** [comment]
A running example would be nice.
Like something you can run with 'make dock_test'.
People don't like to write a config file by hand from scratch; it is better if there is a correct template
that just needs to be tweaked a little.

**Comment by jaimergp** [comment]
Well, the [examples](https://github.com/insilichem/gaudi/tree/master/examples) directory does contain a sample input file which contains all available genes and objectives, with all the parameters, both optional and compulsory. You can tailor an input file from that one just by stripping the unneeded blocks.

I'd start with two `Molecule` genes (Ligand and Protein), and a `Search` and `Torsion` genes applied on the Ligand. For the evaluation part, just use `Clashes` minimization and `HBonds` maximization and see what happens.

I'll upload a zip file with a runnable example shortly.

**Comment by jaimergp** [comment]
Hi!

This zip contains the files needed to run a docking test for the system 1VRH. Unzip it and run it with `gaudi run docking_1vrh.yaml` from the terminal. Let me know if this is enough!

[gaudi-docking-test.zip](https://github.com/insilichem/gaudi/files/1254467/gaudi-docking-test.zip)

**Comment by UnixJunkie** [comment]
if it runs for you, then it is a good enough example and should be added to the corresponding directory.
I looked the YAML file. There are several magic numbers (constants I don't know where they come from / what they mean) but it looks understandable.

**Comment by jaimergp** [comment]
Hi, thanks for the review.

Most of the core functions of GaudiMM are self-documented (if not all), but I understand that accessing the API documentation is not very straight-forward. Anyway, all the 'magic numbers' (or default config values) are discussed in the `gaudi.parse.Settings` class docstring:

http://gaudi.readthedocs.io/en/latest/api/gaudi.html#gaudi.parse.Settings

**Comment by jotjot** [comment]
Thank you!!! I was looking for such an example as well.

**Comment by UnixJunkie** [comment]
In the docking example, is the binding site described by a 12A sphere centered on the ligand?

**Comment by UnixJunkie** [comment]
A sphere with explicit center and radius is OK.
A 3D point with allowed +/- dx, dy and dz is also standard.

**Comment by jaimergp** [comment]
> In the docking example, is the binding site described by a 12A sphere centered on the ligand?

If memory serves, yes! More info: https://gaudi.readthedocs.io/en/latest/api/gaudi.genes.html#module-gaudi.genes.search

**Comment by UnixJunkie** [comment]
ok, thanks for the info
