### ISSUE TITLE
Error when running gaudi for the first time

### ISSUE THREAD

**Issue by MerAle** [insilichem/gaudi#15]
Hi! There is an error coming up when trying to run Gaudi. 
This is the information you want:

On  Ubuntu 18.04.02 LTS, with the followin sorted list of environments:

CHIMERADIR=/opt/UCSF/Chimera64-1.13.1
CLUTTER_IM_MODULE=xim
COLORTERM=truecolor
CONDA_DEFAULT_ENV=insilichem
CONDA_EXE=/home/gja_95/miniconda2/bin/conda
CONDA_PREFIX_1=/home/gja_95/miniconda2
CONDA_PREFIX=/home/gja_95/miniconda2/envs/insilichem
CONDA_PROMPT_MODIFIER=(insilichem) 
CONDA_PYTHON_EXE=/home/gja_95/miniconda2/bin/python
CONDA_SHLVL=2
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_AUTOSTART_ID=1016070c1866ba60b7155337562287089300000010520007
DESKTOP_SESSION=ubuntu
DISPLAY=:0
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SHELL_SESSION_MODE=ubuntu
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/171be68e_f490_4ac7_9647_5f843040b708
GNOME_TERMINAL_SERVICE=:1.100
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
HOME=/home/gja_95
IM_CONFIG_PHASE=2
LANG=ca_ES.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=gja_95
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
OLDPWD=/home/gja_95/Baixades
PATH=/home/gja_95/miniconda2/envs/insilichem/bin:/home/gja_95/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/gja_95/Baixades/Prova
QT4_IM_MODULE=xim
QT_ACCESSIBILITY=1
QT_IM_MODULE=xim
SESSION_MANAGER=local/Ubuntu-Gil:@/tmp/.ICE-unix/1052,unix/Ubuntu-Gil:/tmp/.ICE-unix/1052
SHELL=/bin/bash
SHLVL=1
SSH_AGENT_PID=1167
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
TEXTDOMAINDIR=/usr/share/locale/
TEXTDOMAIN=im-config
USER=gja_95
USERNAME=gja_95
_=/usr/bin/env
VTE_VERSION=5202
WINDOWPATH=1
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_ID=1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
XMODIFIERS=@im=ibus

The commands used to install were the ones found in https://gaudi.readthedocs.io/en/latest/installation.html. 
When running the first calculation with command " gaudi run input.yaml " the following error comes up:

File "/home/gja_95/miniconda2/envs/insilichem/bin/gaudi", line 11, in <module>
    load_entry_point('gaudi==0.0.6', 'console_scripts', 'gaudi')()
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/gaudi/cli/gaudi_cli.py", line 114, in run
    load_chimera()
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/gaudi/cli/gaudi_cli.py", line 73, in load_chimera
    pychimera.enable_chimera()
  File "/home/gja_95/miniconda2/envs/insilichem/lib/python2.7/site-packages/pychimera/core.py", line 67, in enable_chimera
    nogui=nogui, eventloop=not nogui, exitonquit=not nogui)
  File "/opt/UCSF/Chimera64-1.13.1/share/chimeraInit.py", line 666, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.13.1/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: /opt/UCSF/Chimera64-1.13.1/lib/libgfxinfo.so: undefined symbol: _ZN7pcrecpp2RE4InitERKSsPKNS_10RE_OptionsE

Thank you!

**Comment by jaimergp** [comment]
Hi, this is discussed in the [pychimera FAQ](https://github.com/insilichem/pychimera/blob/master/docs/faq.rst).

In a nutshell, you should be able to fix it with:
```
conda activate insilichem
conda install pcre=8.39
```

**Comment by MerAle** [comment]
Hi, 
following your instructions we encounter the following error:

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - imp
  - pcre=8.39

What can we do to solve this?

Thank you!

**Comment by jaimergp** [comment]
This is not happening in the Travis builds :/ Please run:

```
conda activate insilichem
conda info -a
conda list
```

and paste the output here (wrap it in triple backticks: ```)


As a workaround, this could work, but also destabilize the environment (you would have to reinstall). Just get rid of pcre altogether:

`conda remove --force pcre`

**Comment by MerAle** [comment]
By removing pcre the calculation is now running!

I send you the info anyway:

conda info -a
```
active environment : insilichem
    active env location : /home/gja_95/miniconda2/envs/insilichem
            shell level : 2
       user config file : /home/gja_95/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /home/gja_95/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/gja_95/miniconda2/pkgs
                          /home/gja_95/.conda/pkgs
       envs directories : /home/gja_95/miniconda2/envs
                          /home/gja_95/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/2.7.15 Linux/4.18.0-16-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /home/gja_95/miniconda2
insilichem            *  /home/gja_95/miniconda2/envs/insilichem
pychimera_test           /home/gja_95/miniconda2/envs/pychimera_test

sys.version: 2.7.15 |Anaconda, Inc.| (default, Dec 14...
sys.prefix: /home/gja_95/miniconda2
sys.executable: /home/gja_95/miniconda2/bin/python
conda location: /home/gja_95/miniconda2/lib/python2.7/site-packages/conda
conda-build: None
conda-env: /home/gja_95/miniconda2/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: insilichem
CONDA_EXE: /home/gja_95/miniconda2/bin/conda
CONDA_PREFIX: /home/gja_95/miniconda2/envs/insilichem
CONDA_PREFIX_1: /home/gja_95/miniconda2
CONDA_PROMPT_MODIFIER: (insilichem) 
CONDA_PYTHON_EXE: /home/gja_95/miniconda2/bin/python
CONDA_ROOT: /home/gja_95/miniconda2
CONDA_SHLVL: 2
PATH: /home/gja_95/miniconda2/envs/insilichem/bin:/home/gja_95/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
WINDOWPATH: 1


WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

conda list
```
# packages in environment at /home/gja_95/miniconda2/envs/insilichem:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py27_0  
ambermini                 16.16.0                       7    omnia
asn1crypto                0.24.0                   py27_0  
autodock-vina             1.1.2                         1    bioconda
autodocktools-prepare     1.5.7                    py27_0    insilichem
babel                     2.6.0                    py27_0  
blas                      1.0                    openblas  
blosc                     1.15.0               hd408876_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
cclib                     1.5                      py27_0    omnia
certifi                   2019.3.9                 py27_0  
cffi                      1.12.2           py27h2e261b9_1  
cgal                      4.12                 hf484d3e_6    salilab
chardet                   3.0.4                    py27_1  
cryptography              2.6.1            py27h1ba5d50_0  
distribute                0.6.45                   py27_1  
docutils                  0.14                     py27_0  
enum34                    1.1.6                    py27_1  
ffmpeg                    4.0                  hcdf2ecd_0  
fftw                      3.3.4                         0    salilab
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                         1    omnia
freetype                  2.9.1                h8a8886c_1  
gaudi                     0.0.6                    py27_0    insilichem
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
graphite2                 1.3.13               h23475e2_0  
gsl                       2.4                  h2c0fa48_2    salilab
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py27_0  
imagesize                 1.1.0                    py27_0  
imp                       2.10.1           py27hf484d3e_1    salilab
ipaddress                 1.0.22                   py27_0  
jasper                    2.0.14               h07fcdf6_1  
jinja2                    2.10                     py27_0  
jpeg                      9b                   h024ee3a_2  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libopenblas               0.3.3                h5a2b251_3  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.36               hbc83047_0  
libprotobuf               3.6.1                hd408876_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtau                    1.0.2                hf484d3e_0    salilab
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.1            py27h7b6447c_0  
mdtraj                    1.9.1                    py27_0    omnia
mpfr                      4.0.1                hdf1c602_3  
mpich2                    1.4.1p1                       0  
ncurses                   6.1                  he6710b0_1  
nomkl                     3.0                           0  
numexpr                   2.6.9            py27h2ffa06c_0  
numpy                     1.16.2           py27h99e49ec_0  
numpy-base                1.16.2           py27h2f8d375_0  
numpydoc                  0.8.0                    py27_0  
opencv                    3.4.2            py27h6fd60c2_1  
openmm                    7.3.1           py27_cuda92_rc_2    omnia
openmoltools              0.8.3                    py27_1    omnia
openssl                   1.1.1b               h7b6447c_1  
packaging                 19.0                     py27_0  
pandas                    0.24.2           py27he6710b0_0  
parmed                    3.1.0                    py27_0    omnia
pcre                      8.43                 he6710b0_0  
pdbfixer                  1.5                      py27_0    omnia
pip                       19.0.3                   py27_0  
pixman                    0.38.0               h7b6447c_0  
protobuf                  3.6.1            py27he6710b0_0  
py-opencv                 3.4.2            py27hb342d67_1  
pychimera                 0.2.1            py27h9188f34_0    insilichem
pycparser                 2.19                     py27_0  
pygments                  2.3.1                    py27_0  
pyopenssl                 19.0.0                   py27_0  
pyparsing                 2.3.1                    py27_0  
pysocks                   1.6.8                    py27_0  
pytables                  3.4.4            py27ha205bf6_0  
python                    2.7.16               h9bab390_0  
python-dateutil           2.8.0                    py27_0  
pytz                      2018.9                   py27_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py27_0  
scipy                     1.2.1            py27he2b7bc3_0  
setuptools                40.8.0                   py27_0  
six                       1.12.0                   py27_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.8.5                    py27_0  
sphinxcontrib             1.0                      py27_1  
sphinxcontrib-websupport  1.1.0                    py27_1  
sqlite                    3.27.2               h7b6447c_0  
system                    5.8                           2  
tk                        8.6.8                hbc83047_0  
typing                    3.5.2.2                  py27_0    bioconda
urllib3                   1.24.1                   py27_0  
wheel                     0.33.1                   py27_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
```
